### ISSUE TITLE
Crash after uploading image

### ISSUE THREAD

**Issue by matthijs166** [invakid404/payload-blurhash-plugin#1]
When I upload a new image I get the error;
```
TypeError: Cannot read properties of undefined (reading 'config')
    at getMediaDirectory (C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\src\index.ts:11:32)
    at C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\src\index.ts:64:24
    at step (C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\lib\index.js:67:23)
    at Object.next (C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\lib\index.js:48:53)
    at C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\lib\index.js:42:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\lib\index.js:38:12)
    at hook (C:\Users\*\Documents\*\backend\node_modules\payload-blurhash-plugin\lib\index.js:102:20)
    at C:\Users\*\Documents\*\backend\node_modules\payload\src\collections\operations\update.ts:176:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
    
    "payload": "^1.0.11",

**Comment by invakid404** [comment]
@matthijs166 thanks a lot for the PR, I've merged it and confirmed the plugin works as expected with Payload 1.0.11 now. I'll release a new version shortly :^)

**Comment by matthijs166** [comment]
@invakid404 Awesome your a hero!
